# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c30cea38fd235ba1b6f5a5da4f74bd5257fdee1e2a87f286ee2ef280dd21beeb5210b9a1858cc51953591a9b6f2871d5fc58ae7985dfd0b2404626b8cb31fd4

test:
  secret_key_base: 4dbd42b2430332cd2e520c533aa68c7b2e952a4a341088b9fbe06a75bd8a76337e4527a4bed4b79cf4dcd33236b5abe36ddca28eacdbd74327a360ac5820fa25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
